### ISSUE TITLE
Module does not support Netbox Instances with "Always logon" set

### ISSUE THREAD

**Issue by RobinBeismann** [BatmanAMA/powerbox#11]
The Invoke-nbApi.ps1 does not support netbox instances which require login even for reading data.
This is related to line 108, which is checking "$HttpVerb -ne $get)".

Requests with "GET" HTTP Method won't get the Authorization Header attached and thus fail.

Is it possible to either include a further parameter for Connect-nbAPI or some other check?

Thanks!

**Comment by BatmanAMA** [comment]
Thanks for calling that out - I'll put that in the next patch which shouldn't be too far away.
