### ISSUE TITLE
Module doesn't allow large API Querys

### ISSUE THREAD

**Issue by RobinBeismann** [BatmanAMA/powerbox#12]
Hi again,

is it possible to implement either a parameter or a settings variable for the request limit?
The GET Parameter for this is ?limit=number, for example ?limit=0 will return unlimited much results, useful for IP Address requests and stuff like that.
I've added it a new line at line 73 in Invoke-nbAPI.ps1 setting $Query["limit"] = "0" so it gets attached to the request, however I'm sure there are cleaner ways.

**Comment by BatmanAMA** [comment]
Hey Robin. - I just put out a [prerelease version](https://github.com/BatmanAMA/powerbox/releases/tag/vupdate-2.2.x-prerelease) to address your issues if you'd like to test it out. Plan on finishing it and publishing to PSGallery early next week.

**Comment by RobinBeismann** [comment]
Hey Josh,

I'll try it out once I'm at work again (on vacation right now), we're using this modul to import VMs, NICs, Subnets and IPs from the System Center Virtual Machine Manager into Netbox.

**Comment by RobinBeismann** [comment]
Yes, this worked, thanks.
However you didn't merge in the patch for the #11 yet, did you? I had to remote the clause which disables authentication for GET Requests.
