### ISSUE TITLE
[new-nbInterface] Can't get it to work

### ISSUE THREAD

**Issue by MakwaWes** [BatmanAMA/powerbox#22]
Hi,

I'm discovering your module and it's pretty awesome work you did there !

I'm trying to add an interface to a device but while issuing the cmdlet "New-nbInterface -Object @{'name' = 'test';'device'=14307} -Verbose", I keep getting a "400 bad request" error.
After checking the code, the body object sent by "new-nbObject" is having too much properties.
It looks like this :
```
Key   : Body
Value : {"Count":2,"IsFixedSize":false,"custom_fields":{},"IsSynchronized":false,"IsReadOnly":false,"Keys":["name","device"],"Values":["test",14307],"SyncRoot":{}}
Name  : Body
```
Any idea ?
Thanks.

**Comment by MakwaWes** [comment]
Just found out why it didn't work .... I wasn't using the good object declaration. It must be a PSCustomObject type, not a hashtable.
For the records :
```
$MyNewNetBoxObject = [PScustomObject]@{ 'name' = 'newobjectname';'otherprop' = 'my value'}
```

**Comment by BatmanAMA** [comment]
That's a good call out for me to make more clear in the documentation. All the commands expect to receive an object, and will fail on hashtables. It might be a future improvement to make them check for hashtables and convert them to objects.
