### ISSUE TITLE
Cant seem to set the primary_ipv4 attribute of devices

### ISSUE THREAD

**Issue by andreaalloway** [BatmanAMA/powerbox#24]
Hello,
I can't seem to get the Set-nbDevice to update the Primary IP
Example code:

`
$query = @{
	device_id = $myDevice.id
}
$nics = Get-nbInterface -Query $query

$nbnic = $nics | Where-Object {$_.mac_address -eq $mac}

$query = @{
	interface_id = $nbnic.id
}
$nicIP = Get-nbIpAddress -Query $query

$updateNic = [PScustomObject]@{
	primary_ipv4 = $nicIP.id
}
$myDevice = Set-nbDevice -ID $myDevice.id -Object $updateNic -Patch

`

Any Ideas?
$myDevice is returned properly from a previous Get-nbDevice query
$nicIP.id is properly populated.

**Comment by BatmanAMA** [comment]
Howdy - 

Sorry I didn't notice this before. That code is very similar to what I'm running for my inventory script so I'm not sure what is happening. I just released a patch to fix some error handling that has been annoying me and add in some debug output. I'm going to test it and then release it to the PS Gallery in the next day or so - I'd be interested in seeing what you'll get running the set-nbdevice with the -verbose and -debug switches, especially with the patch to error handling.

**Comment by MakwaWes** [comment]
Hi,

I think it's because of a typo in the property you are trying to update : _primary_ipv4_. It should be **primary_ip4**.
```
(Get-nbDevice -Id $myDevice.id).psobject.Properties.name | ?{ $_ -like '*ip*4*'}
```

**Comment by BatmanAMA** [comment]
That would do it. Good Catch!
