### ISSUE TITLE
Will this be updated to the newest features of netbox in the future?

### ISSUE THREAD

**Issue by tkn2023** [BatmanAMA/powerbox#46]
Since there are major updates to netbox including the new "virtual disks" it would be great to have this function also in the powerbox powershell module.
Since the last update to this module has been over 2 years ago, I just wanted to ask if this will be updated or not

**Comment by BatmanAMA** [comment]
Hello! My regrets, I left the position that gave me access to the resources and time to work on this :( - I won't rule it out, but it really depends on if I can convince my new employer to use netbox. If you would like to fork it, you are more than welcome to - though I'll be honest with some of the newer rest tooling in PS7+, if I were coming back at it it would likely be a significant rewrite.
